---
apiVersion: v1
kind: Pod
metadata:
  name: netkit
  labels:
    app.kubernetes.io/name: netkit
spec:
  containers:
    - name: netkit
      image: ghcr.io/self-hosters-by-night/netkit:latest
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
          add:
            - NET_RAW
            - NET_ADMIN
  restartPolicy: Never
